/*
 * Simple List of Countries
 * */
module.exports = {
    Albania: "Albania",
    Algeria: "Algeria",
    Andorra: "Andorra",
    Angola: "Angola",
    AntiguaAndBarbuda: "Antigua and Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Australia: "Australia",
    AshmoreAndCartierIslands: "Ashmore and Cartier Islands",
    AustralianAntarcticTerritory: "Australian Antarctic Territory",
    ChristmasIsland: "Christmas Island",
    CocosIslands: "Cocos (Keeling) Islands",
    CoralSeaIslandsTerritory: "Coral Sea Islands Territory",
    HeardIslandAndMcDonaldIslands: "Heard Island and McDonald Islands",
    NorfolkIsland: "Norfolk Island",
    Austria: "Austria",
    Azerbaijan: "Azerbaijan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrain",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belgium",
    Belize: "Belize",
    Benin: "Benin",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    BosniaAndHerzegovina: "Bosnia and Herzegovina",
    BosniaAndHerzegovina: "Federation of Bosnia and Herzegovina",
    RepublikaSrpska: "Republika Srpska",
    Botswana: "Botswana",
    Brazil: "Brazil",
    Brunei: "Brunei",
    Bulgaria: "Bulgaria",
    BurkinaFaso: "Burkina Faso",
    Burma: "Burma",
    Burundi: "Burundi",
    Cambodia: "Cambodia",
    Cameroon: "Cameroon",
    Canada: "Canada",
    CapeVerde: "Cape Verde",
    CentralAfricanRepublic: "Central African Republic",
    Chad: "Chad",
    Chile: "Chile",
    China: "China",
    HongKong: "Hong Kong",
    Macau: "Macau",
    Colombia: "Colombia",
    Comoros: "Comoros",
    Congo: "Congo",
    CostaRica: "Costa Rica",
    Croatia: "Croatia",
    Cuba: "Cuba",
    Cyprus: "Cyprus",
    CzechRepublic: "Czech Republic",
    Denmark: "Denmark",
    FaroeIslands: "Faroe Islands",
    Greenland: "Greenland",
    Djibouti: "Djibouti",
    Dominica: "Dominica",
    DominicanRepublic: "Dominican Republic",
    EastTimor: "East Timor",
    Ecuador: "Ecuador",
    Egypt: "Egypt",
    ElSalvador: "El Salvador",
    EquatorialGuinea: "Equatorial Guinea",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Ethiopia: "Ethiopia",
    Fiji: "Fiji",
    Finland: "Finland",
    Åland: "Åland",
    France: "France",
    ClippertonIsland: "Clipperton Island",
    FrenchPolynesia: "French Polynesia",
    NewCaledonia: "New Caledonia",
    SaintBarthélemy: "Saint Barthélemy",
    SaintMartin: "Saint Martin",
    SaintPierreAndMiquelon: "Saint Pierre and Miquelon",
    WallisAndFutuna: "Wallis and Futuna",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Germany: "Germany",
    Ghana: "Ghana",
    Greece: "Greece",
    Grenada: "Grenada",
    Guatemala: "Guatemala",
    Guinea: "Guinea",
    GuineaBissau: "Guinea Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    Honduras: "Honduras",
    Hungary: "Hungary",
    Iceland: "Iceland",
    India: "India",
    Indonesia: "Indonesia",
    Iran: "Iran",
    Iraq: "Iraq",
    Ireland: "Ireland",
    Israel: "Israel",
    Italy: "Italy",
    IvoryCoast: "Ivory Coast",
    Jamaica: "Jamaica",
    Japan: "Japan",
    Jordan: "Jordan",
    Kazakhstan: "Kazakhstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    NorthKorea: "North Korea",
    SouthKorea: "South Korea",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kyrgyzstan",
    Laos: "Laos",
    Latvia: "Latvia",
    Lebanon: "Lebanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    Libya: "Libya",
    Cyrenaica: "Cyrenaica",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lithuania",
    Luxembourg: "Luxembourg",
    Macedonia: "Macedonia",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldives",
    Mali: "Mali",
    Malta: "Malta",
    MarshallIslands: "Marshall Islands",
    Mauritania: "Mauritania",
    Mauritius: "Mauritius",
    Mexico: "Mexico",
    Micronesia: "Micronesia",
    Moldova: "Moldova",
    Monaco: "Monaco",
    Mongolia: "Mongolia",
    Montenegro: "Montenegro",
    Morocco: "Morocco",
    Mozambique: "Mozambique",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Netherlands",
    Netherlands: "Netherlands",
    Aruba: "Aruba",
    Curaçao: "Curaçao",
    SintMaarten: "Sint Maarten",
    NewZealand: "New Zealand",
    RossDependency: "Ross Dependency",
    Tokelau: "Tokelau",
    CookIslands: "Cook Islands",
    Niue: "Niue",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Norway: "Norway",
    Oman: "Oman",
    Pakistan: "Pakistan",
    AzadKashmir: "Azad Kashmir",
    GilgitBaltistan: "Gilgit–Baltistan",
    Palau: "Palau",
    Palestine: "Palestine",
    Panama: "Panama",
    PapuaNewGuinea: "Papua New Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Philippines",
    Poland: "Poland",
    Portugal: "Portugal",
    Qatar: "Qatar",
    Romania: "Romania",
    Russia: "Russia",
    Rwanda: "Rwanda",
    SaintKittsAndNevis: "Saint Kitts and Nevis",
    SaintLucia: "Saint Lucia",
    SaintVincentAndGrenadines: "Saint Vincent and the Grenadines",
    Samoa: "Samoa",
    SanMarino: "San Marino",
    SaoTomeAndPrincipe: "São Tomé and Príncipe",
    SaudiArabia: "Saudi Arabia",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Seychelles: "Seychelles",
    SierraLeone: "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovakia",
    Slovenia: "Slovenia",
    SolomonIslands: "Solomon Islands",
    Somalia: "Somalia",
    SouthAfrica: "South Africa",
    SouthSudan: "South Sudan",
    Spain: "Spain",
    SriLanka: "Sri Lanka",
    Sudan: "Sudan",
    Suriname: "Suriname",
    Swaziland: "Swaziland",
    Sweden: "Sweden",
    Switzerland: "Switzerland",
    Syria: "Syria",
    Tajikistan: "Tajikistan",
    Tanzania: "Tanzania",
    Thailand: "Thailand",
    Togo: "Togo",
    Tonga: "Tonga",
    TrinidadAndTobago: "Trinidad and Tobago",
    Tunisia: "Tunisia",
    Turkey: "Turkey",
    Turkmenistan: "Turkmenistan",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraine",
    UnitedArabEmirates: "United Arab Emirates",
    UnitedKingdom: "United Kingdom",
    AkrotiriAndDhekelia: "Akrotiri and Dhekelia",
    Anguilla: "Anguilla",
    Bermuda: "Bermuda",
    BritishIndianOceanTerritory: "British Indian Ocean Territory",
    BritishVirginIslands: "British Virgin Islands",
    CaymanIslands: "Cayman Islands",
    FalklandIslands: "Falkland Islands",
    Gibraltar: "Gibraltar",
    Montserrat: "Montserrat",
    PitcairnIslands: "Pitcairn Islands",
    SaintHelena: "Saint Helena",
    AscensionAndTristanCunha: " Ascension and Tristan da Cunha",
    Guernsey: "Guernsey",
    Alderney: "Alderney",
    Herm: "Herm",
    Sark: "Sark",
    IsleOfMan: "Isle of Man",
    Jersey: "Jersey",
    UnitedStates: "United States",
    AmericanSamoa: "American Samoa",
    Guam: "Guam",
    PuertoRico: "Puerto Rico",
    Micronesia: "Micronesia",
    Palau: "Palau",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    VaticanCity: "Vatican City",
    Venezuela: "Venezuela",
    Vietnam: "Vietnam",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
    Abkhazia: "Abkhazia",
    CookIslands: "Cook Islands",
    Kosovo: "Kosovo",
    NagornoKarabakh: "Nagorno-Karabakh",
    Niue: "Niue",
    NorthernCyprus: "Northern Cyprus",
    SahrawiArabDemocraticRepublic: "Sahrawi Arab Democratic Republic",
    Somaliland: "Somaliland",
    SouthOssetia: "South Ossetia",
    Taiwan: "Taiwan"
};