/*
 * Simple List of Currencies
 * */
module.exports = {
    AED: "AED", // "United Arab Emirates Dirham",
    AFN: "AFN", // "Afghan Afghani",
    ALL: "ALL", // "Albanian Lek",
    AMD: "AMD", // "Armenian Dram",
    ANG: "ANG", // "Netherlands Antillean Guilder",
    AOA: "AOA", // "Angolan Kwanza",
    ARS: "ARS", // "Argentine Peso",
    AUD: "AUD", // "Australian Dollar",
    AWG: "AWG", // "Aruban Florin",
    AZN: "AZN", // "Azerbaijani Manat",
    BAM: "BAM", // "Bosnia-Herzegovina Convertible Mark",
    BBD: "BBD", // "Barbadian Dollar",
    BDT: "BDT", // "Bangladeshi Taka",
    BGN: "BGN", // "Bulgarian Lev",
    BHD: "BHD", // "Bahraini Dinar",
    BIF: "BIF", // "Burundian Franc",
    BMD: "BMD", // "Bermudan Dollar",
    BND: "BND", // "Brunei Dollar",
    BOB: "BOB", // "Bolivian Boliviano",
    BRL: "BRL", // "Brazilian Real",
    BSD: "BSD", // "Bahamian Dollar",
    BTC: "BTC", // Bitcoin
    BTN: "BTN", // "Bhutanese Ngultrum",
    BWP: "BWP", // "Botswanan Pula",
    BYR: "BYR", // "Belarusian Ruble",
    BZD: "BZD", // "Belize Dollar",
    CAD: "CAD", // "Canadian Dollar",
    CDF: "CDF", // "Congolese Franc",
    CHF: "CHF", // "Swiss Franc",
    CLF: "CLF", // "Chilean Unit of Account (UF)",
    CLP: "CLP", // "Chilean Peso",
    CNC: "CNC", // "Chinacoin",
    CNY: "CNY", // "Chinese Yuan",
    COP: "COP", // "Colombian Peso",
    CRC: "CRC", // "Costa Rican Colón",
    CUP: "CUP", // "Cuban Peso",
    CVE: "CVE", // "Cape Verdean Escudo",
    CZK: "CZK", // "Czech Republic Koruna",
    DJF: "DJF", // "Djiboutian Franc",
    DKK: "DKK", // "Danish Krone",
    DOGE: "DOGE", // "Dogecoin",
    DOP: "DOP", // "Dominican Peso",
    DGC: "DGC", // Digitalcoin,
    DVC: "DVC", // Devcoin,
    XDC: "DOGE", // Dogecoin,
    DRK: "DRK", // "Darkcoin",
    DZD: "DZD", // "Algerian Dinar",
    EEK: "EEK", // "Estonian Kroon",
    EGP: "EGP", // "Egyptian Pound",
    ETB: "ETB", // "Ethiopian Birr",
    EUR: "EUR", // "Euro",
    FJD: "FJD", // "Fijian Dollar",
    FKP: "FKP", // "Falkland Islands Pound",
    FTC: "FTC", // "Feathercoin",
    GBP: "GBP", // "British Pound Sterling",
    GEL: "GEL", // "Georgian Lari",
    GHS: "GHS", // "Ghanaian Cedi",
    GHs: "GHS", // "Gigahashes per second",
    GIP: "GIP", // "Gibraltar Pound",
    GMD: "GMD", // "Gambian Dalasi",
    GNF: "GNF", // "Guinean Franc",
    GTQ: "GTQ", // "Guatemalan Quetzal",
    GYD: "GYD", // "Guyanaese Dollar",
    HKD: "HKD", // "Hong Kong Dollar",
    HNL: "HNL", // "Honduran Lempira",
    HRK: "HRK", // "Croatian Kuna",
    HTG: "HTG", // "Haitian Gourde",
    HUF: "HUF", // "Hungarian Forint",
    IDR: "IDR", // "Indonesian Rupiah",
    ILS: "ILS", // "Israeli New Sheqel",
    INR: "INR", // "Indian Rupee",
    IQD: "IQD", // "Iraqi Dinar",
    IRR: "IRR", // "Iranian Rial",
    ISK: "ISK", // "Icelandic Króna",
    IXC: "IXC", // iXcoin,
    JEP: "JEP", // "Jersey Pound",
    JMD: "JMD", // "Jamaican Dollar",
    JOD: "JOD", // "Jordanian Dinar",
    JPY: "JPY", // "Japanese Yen",
    KES: "KES", // "Kenyan Shilling",
    KGS: "KGS", // "Kyrgystani Som",
    KHR: "KHR", // "Cambodian Riel",
    KMF: "KMF", // "Comorian Franc",
    KPW: "KPW", // "North Korean Won",
    KRW: "KRW", // "South Korean Won",
    KWD: "KWD", // "Kuwaiti Dinar",
    KYD: "KYD", // "Cayman Islands Dollar",
    KZT: "KZT", // "Kazakhstani Tenge",
    LAK: "LAK", // "Laotian Kip",
    LBP: "LBP", // "Lebanese Pound",
    LKR: "LKR", // "Sri Lankan Rupee",
    LRD: "LRD", // "Liberian Dollar",
    LSL: "LSL", // "Lesotho Loti",
    LTC: "LTC", // "Litecoin",
    LTL: "LTL", // "Lithuanian Litas",
    LVL: "LVL", // "Latvian Lats",
    LYD: "LYD", // "Libyan Dinar",
    MAD: "MAD", // "Moroccan Dirham",
    MDL: "MDL", // "Moldovan Leu",
    MEC: "MEC", // "MegaCoin",
    MGA: "MGA", // "Malagasy Ariary",
    MKD: "MKD", // "Macedonian Denar",
    MMK: "MMK", // "Myanma Kyat",
    MNT: "MNT", // "Mongolian Tugrik",
    MOP: "MOP", // "Macanese Pataca",
    MRO: "MRO", // "Mauritanian Ouguiya",
    MSC: "MSC", // "Mason Coin",
    MUR: "MUR", // "Mauritian Rupee",
    MVR: "MVR", // "Maldivian Rufiyaa",
    MWK: "MWK", // "Malawian Kwacha",
    MXN: "MXN", // "Mexican Peso",
    MYR: "MYR", // "Malaysian Ringgit",
    MZN: "MZN", // "Mozambican Metical",
    NAD: "NAD", // "Namibian Dollar",
    NGN: "NGN", // "Nigerian Naira",
    NIO: "NIO", // "Nicaraguan Córdoba",
    //NMC: "NMC", // Namecoin,
    NOK: "NOK", // "Norwegian Krone",
    NPR: "NPR", // "Nepalese Rupee",
    NVC: "NVC", // "Novacoin",
    NXT: "NXT", // "Nextcoin",
    NZD: "NZD", // "New Zealand Dollar",
    OMR: "OMR", // "Omani Rial",
    PAB: "PAB", // "Panamanian Balboa",
    PEN: "PEN", // "Peruvian Nuevo Sol",
    PGK: "PGK", // "Papua New Guinean Kina",
    PHP: "PHP", // "Philippine Peso",
    PKR: "PKR", // "Pakistani Rupee",
    PLN: "PLN", // "Polish Zloty",
    PPC: "PPC", // "Peercoin",
    PYG: "PYG", // "Paraguayan Guarani",
    QAR: "QAR", // "Qatari Rial",
    QRK: "QRK", // "QuarkCoin",
    RON: "RON", // "Romanian Leu",
    RSD: "RSD", // "Serbian Dinar",
    RUB: "RUB", // "Russian Ruble",
    RUR: "RUR", // "Old Russian Ruble",
    RWF: "RWF", // "Rwandan Franc",
    SAR: "SAR", // "Saudi Riyal",
    SBC: "SBC", // "Stablecoin",
    SBD: "SBD", // "Solomon Islands Dollar",
    SCR: "SCR", // "Seychellois Rupee",
    SDG: "SDG", // "Sudanese Pound",
    SEK: "SEK", // "Swedish Krona",
    SGD: "SGD", // "Singapore Dollar",
    SHP: "SHP", // "Saint Helena Pound",
    SLL: "SLL", // "Sierra Leonean Leone",
    SOS: "SOS", // "Somali Shilling",
    SRD: "SRD", // "Surinamese Dollar",
    STD: "STD", // "São Tomé and Príncipe Dobra",
    SVC: "SVC", // "Salvadoran Colón",
    SYP: "SYP", // "Syrian Pound",
    SZL: "SZL", // "Swazi Lilangeni",
    THB: "THB", // "Thai Baht",
    TJS: "TJS", // "Tajikistani Somoni",
    TMT: "TMT", // "Turkmenistani Manat",
    TND: "TND", // "Tunisian Dinar",
    TOP: "TOP", // "Tongan Paʻanga",
    TRC: "TRC", // "Terracoin",
    TRY: "TRY", // "Turkish Lira",
    TTD: "TTD", // "Trinidad and Tobago Dollar",
    TWD: "TWD", // "New Taiwan Dollar",
    TZS: "TZS", // "Tanzanian Shilling",
    UAH: "UAH", // "Ukrainian Hryvnia",
    UGX: "UGX", // "Ugandan Shilling",
    USD: "USD", // "United States Dollar",
    UTC: "UTC", // Ultracoin,
    UYU: "UYU", // "Uruguayan Peso",
    UZS: "UZS", // "Uzbekistan Som",
    VEF: "VEF", // "Venezuelan Bolívar",
    VEN: "VEN", // Hub Culture's Ven,
    VND: "VND", // "Vietnamese Dong",
    VUV: "VUV", // "Vanuatu Vatu",
    WDC: "WDC", // "WorldCoin",
    WST: "WST", // "Samoan Tala",
    XAF: "XAF", // "CFA Franc BEAC",
    XBT: "XBT", // Bitcoin,
    XCD: "XCD", // "East Caribbean Dollar",
    XDR: "XDR", // "Special Drawing Rights",
    XOF: "XOF", // "CFA Franc BCEAO",
    XPF: "XPF", // "CFP Franc",
    XPM: "XPM", // "Primecoin",
    XRP: "XRP", // Ripple
    XVN: "XVN", // Hub Culture's Ven,
    YER: "YER", // "Yemeni Rial",
    ZAR: "ZAR", // "South African Rand",
    ZMK: "ZMK", // "Zambian Kwacha",
    ZWL: "ZWL", // "Zimbabwean Dollar"
};
